# Source embedding size (400) != model embedding size (200).
class_path: yoyodyne.models.AttentiveLSTMModel
init_args:
  source_encoder:
    class_path: yoyodyne.models.modules.LSTMEncoder
    init_args:
      dropout: .3
      embedding_size: 400
      hidden_size: 100
  decoder_dropout: .3
  decoder_hidden_size: 100
  embedding_size: 200
  optimizer:
    class_path: torch.optim.Adadelta
    init_args:
      lr: 1
