# Features embedding size (128) != model embedding size (256)
class_path: yoyodyne.models.TransformerModel
init_args:
  source_encoder:
    class_path: yoyodyne.models.modules.TransformerEncoder
    init_args:
      dropout: .3
      embedding_size: 256
      hidden_size: 1024
      layers: 4
  features_encoder:
    class_path: yoyodyne.models.modules.TransformerEncoder
    init_args:
      dropout: .3
      embedding_size: 128
      hidden_size: 1024
      layers: 4
  decoder_dropout: .3
  decoder_hidden_size: 100
  decoder_layers: 4
  embedding_size: 256
  label_smoothing: .1
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: .001
  scheduler:
    class_path: yoyodyne.schedulers.WarmupInverseSquareRoot
    init_args:
      warmup_epochs: 10
