# Features embedding size (200) != model embedding size (300)
class_path: yoyodyne.models.AttentiveLSTMModel
init_args:
  source_encoder:
    class_path: yoyodyne.models.modules.LSTMEncoder
    init_args:
      dropout: .3
      embedding_size: 300
      hidden_size: 100
  features_encoder:
    class_path: yoyodyne.models.modules.LinearEncoder
    init_args:
      embedding_size: 200
      output_size: 100
  decoder_dropout: .3
  decoder_hidden_size: 100
  embedding_size: 300
  optimizer:
    class_path: torch.optim.Adadelta
    init_args:
      lr: 1
