# Number of encoder layers (2) and decoder layers (1) must match
class_path: yoyodyne.models.PointerGeneratorLSTMModel
init_args:
  source_encoder:
    class_path: yoyodyne.models.modules.LSTMEncoder
    init_args:
      dropout: .3
      embedding_size: 300
      hidden_size: 100
      layers: 2
  decoder_dropout: .3
  decoder_hidden_size: 100
  embedding_size: 300
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: .001
